server:
  port: 8080
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:mysql://localhost:3306/solicitudes"
    username: "root"
    password: "1994"
  profiles:
    include: null
clients:
  users-service:
    url: "http://localhost:8081"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
